// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.4
// source: server/grpc/proto/delay.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_delay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_delay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_delay_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Replay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Replay) Reset() {
	*x = Replay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_delay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_delay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_delay_proto_rawDescGZIP(), []int{1}
}

func (x *Replay) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Replay) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_server_grpc_proto_delay_proto protoreflect.FileDescriptor

var file_server_grpc_proto_delay_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a,
	0x06, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x35, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x2c,
	0x0a, 0x0d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_grpc_proto_delay_proto_rawDescOnce sync.Once
	file_server_grpc_proto_delay_proto_rawDescData = file_server_grpc_proto_delay_proto_rawDesc
)

func file_server_grpc_proto_delay_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_delay_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_delay_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_grpc_proto_delay_proto_rawDescData)
	})
	return file_server_grpc_proto_delay_proto_rawDescData
}

var file_server_grpc_proto_delay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_grpc_proto_delay_proto_goTypes = []interface{}{
	(*Req)(nil),    // 0: proto.Req
	(*Replay)(nil), // 1: proto.Replay
}
var file_server_grpc_proto_delay_proto_depIdxs = []int32{
	0, // 0: proto.delay.RpcServerTest:input_type -> proto.Req
	1, // 1: proto.delay.RpcServerTest:output_type -> proto.Replay
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_delay_proto_init() }
func file_server_grpc_proto_delay_proto_init() {
	if File_server_grpc_proto_delay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_grpc_proto_delay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_delay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_grpc_proto_delay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_delay_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_delay_proto_depIdxs,
		MessageInfos:      file_server_grpc_proto_delay_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_delay_proto = out.File
	file_server_grpc_proto_delay_proto_rawDesc = nil
	file_server_grpc_proto_delay_proto_goTypes = nil
	file_server_grpc_proto_delay_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DelayClient is the client API for Delay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DelayClient interface {
	RpcServerTest(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Replay, error)
}

type delayClient struct {
	cc grpc.ClientConnInterface
}

func NewDelayClient(cc grpc.ClientConnInterface) DelayClient {
	return &delayClient{cc}
}

func (c *delayClient) RpcServerTest(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Replay, error) {
	out := new(Replay)
	err := c.cc.Invoke(ctx, "/proto.delay/RpcServerTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelayServer is the server API for Delay service.
type DelayServer interface {
	RpcServerTest(context.Context, *Req) (*Replay, error)
}

// UnimplementedDelayServer can be embedded to have forward compatible implementations.
type UnimplementedDelayServer struct {
}

func (*UnimplementedDelayServer) RpcServerTest(context.Context, *Req) (*Replay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcServerTest not implemented")
}

func RegisterDelayServer(s *grpc.Server, srv DelayServer) {
	s.RegisterService(&_Delay_serviceDesc, srv)
}

func _Delay_RpcServerTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelayServer).RpcServerTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.delay/RpcServerTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelayServer).RpcServerTest(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Delay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.delay",
	HandlerType: (*DelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcServerTest",
			Handler:    _Delay_RpcServerTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/grpc/proto/delay.proto",
}
