[redis]
host="192.168.11.53"
port="6379"
password=""
db=0

[bucket]
size=3
name="dq_bucket_%d"

[ticker]
bucket_time=5000000000

[http]
address="0.0.0.0:8112"

[http_client]
max_idle_conns=50
idle_conn_timeout=5000000000
timeout=5000000000

[rpc]
address="0.0.0.0:8972"
network="tcp"

[queue]
execer_url="0.0.0.0:8112"