[redis]
host="192.168.10.172"
port="6379"
password=""
db=0

[bucket]
size=3
name="dq_bucket_%d"

[ticker]
bucket_time=5000000000

[http]
address="0.0.0.0:8112"

[rpc]
address="0.0.0.0:8972"
network="tcp"